name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  schedule:
    # Perform a test run every day at an arbitrarily picked time
    - cron: '17 5 * * *'
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.org'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v1
    - uses: ./
      with:
        config-file: example/.melpa-check
    - run: melpa-check --version
